name: initializer
description: Dependency Injection initializer module
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  common:
    path: ../common
  domain_account:
    path: ../domain_account
  data_account:
    path: ../data_account

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
